# Generated by Django 2.2.7 on 2021-04-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Mammography',
        ),
    ]
