# Generated by Django 2.2.7 on 2021-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammo', '0002_auto_20210429_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammography',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Mammogram/'),
        ),
    ]
